In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
%matplotlib inline

In [2]:
f_data= pd.read_csv("./data_folder/cleaned_data.csv")

In [3]:
f_data.head(3)

,Order_Date,Year,Month,Quarter,Season,Customer_Gender,Customer_Segment,Region,Country,Category,...,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Method,Shipping_Days,Payment_Method,Order_Status
0,2021-01-05,2021,January,Q1,Winter,Female,New,Asia,India,Clothing,...,0.4,112.19,130.29,-18.10,-16.13,18.27,Standard,22,Cash on Delivery,Delivered
1,2021-01-15,2021,January,Q1,Winter,Female,Premium,Middle East,Jordan,Electronics,...,0.5,931.58,870.47,61.11,6.56,37.13,Express,18,Credit Card,Delivered
2,2021-01-20,2021,January,Q1,Winter,Female,Regular,Middle East,Egypt,Electronics,...,0.1,7528.32,3884.40,3643.92,48.40,8.60,Standard,17,Google Pay,Delivered

## Date Feature Engineering

In [4]:
f_data["Order_Date"] = pd.to_datetime(f_data["Order_Date"])

In [5]:
f_data["Order_Date"].dtype

dtype('<M8[ns]')

In [6]:
# assigning the month data
f_data["Order_Month"] = f_data["Order_Date"].dt.month
f_data["Order_Month"].head(2)

0    1
1    1
Name: Order_Month, dtype: int32

In [7]:
## creating the order quarter

f_data["Order_Quarter"] = f_data["Order_Date"].dt.quarter
f_data["Order_Quarter"].head(2)

0    1
1    1
Name: Order_Quarter, dtype: int32

In [8]:
# creating the order year

f_data["Order_Year"] = f_data["Order_Date"].dt.year
f_data["Order_Year"].head(2)

0    2021
1    2021
Name: Order_Year, dtype: int32

## Financial Feature Engineering

In [9]:
## Profit Margin

f_data[["Profit_Margin_%", "Profit", "Revenue"]].head(3)

   Profit_Margin_%   Profit  Revenue
0           -16.13   -18.10   112.19
1             6.56    61.11   931.58
2            48.40  3643.92  7528.32

In [10]:
#revenue / unit

f_data["revenue_per_unit"] = f_data["Revenue"] / f_data["Quantity"]
f_data["revenue_per_unit"].head(2)

0     56.095
1    465.790
Name: revenue_per_unit, dtype: float64

In [11]:
#profit / unit

f_data["profit_per_unit"] = f_data["Profit"] / f_data["Quantity"]
f_data["profit_per_unit"].head(2)

0    -9.050
1    30.555
Name: profit_per_unit, dtype: float64

In [12]:
# shipping cost to revenue ratio

f_data["scost_per_revenue"] = f_data["Shipping_Cost"] / f_data["Revenue"]
f_data["scost_per_revenue"].head(2)

0    0.162849
1    0.039857
Name: scost_per_revenue, dtype: float64

In [13]:
# Net revenue

f_data["net_revenue"] = f_data["Revenue"] / f_data["Shipping_Cost"]
f_data["net_revenue"].head(2)

0     6.140668
1    25.089685
Name: net_revenue, dtype: float64

In [14]:
f_data.head(5)

,Order_Date,Year,Month,Quarter,Season,Customer_Gender,Customer_Segment,Region,Country,Category,...,Shipping_Days,Payment_Method,Order_Status,Order_Month,Order_Quarter,Order_Year,revenue_per_unit,profit_per_unit,scost_per_revenue,net_revenue
0,2021-01-05,2021,January,Q1,Winter,Female,New,Asia,India,Clothing,...,22,Cash on Delivery,Delivered,1,1,2021,56.095,-9.050,0.162849,6.140668
1,2021-01-15,2021,January,Q1,Winter,Female,Premium,Middle East,Jordan,Electronics,...,18,Credit Card,Delivered,1,1,2021,465.790,30.555,0.039857,25.089685
2,2021-01-20,2021,January,Q1,Winter,Female,Regular,Middle East,Egypt,Electronics,...,17,Google Pay,Delivered,1,1,2021,1882.080,910.980,0.001142,875.386047
3,2021-01-22,2021,January,Q1,Winter,Male,VIP,Asia,South Korea,Books & Media,...,17,Debit Card,Delivered,1,1,2021,31.092,12.048,0.367040,2.724501
4,2021-01-25,2021,January,Q1,Winter,Female,Regular,Asia,Japan,Clothing,...,10,Credit Card,Delivered,1,1,2021,123.250,51.795,0.381460,2.621504

In [15]:
f_data.describe()

,Order_Date,Year,Unit_Price,Quantity,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Days,Order_Month,Order_Quarter,Order_Year,revenue_per_unit,profit_per_unit,scost_per_revenue,net_revenue
count,10000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2023-04-06 12:20:18.240000,2022.756300,236.307452,2.731300,0.17675,528.438770,384.674939,143.763831,23.648594,32.299889,11.436100,6.604300,2.530800,2022.756300,194.418493,52.749632,0.393257,43.301326
min,2021-01-05 00:00:00,2021.000000,10.010000,1.000000,0.00000,5.330000,4.850000,-1572.900000,-50.000000,2.000000,3.000000,1.000000,1.000000,2021.000000,5.225000,-468.020000,0.000168,0.073446
25%,2022-09-02 00:00:00,2022.000000,42.767500,1.000000,0.00000,67.227500,50.017500,9.007500,13.497500,8.260000,7.000000,4.000000,2.000000,2022.000000,34.530000,5.110000,0.033317,2.659052
50%,2023-05-13 00:00:00,2023.000000,92.495000,2.000000,0.15000,164.600000,121.395000,34.745000,28.330000,20.300000,10.000000,7.000000,3.000000,2023.000000,74.845000,17.053000,0.114497,8.733847
75%,2023-11-24 00:00:00,2023.000000,221.822500,4.000000,0.30000,469.952500,339.020000,118.475000,39.082500,50.362500,15.000000,10.000000,4.000000,2023.000000,181.838750,48.959375,0.376074,30.014581
max,2024-12-24 00:00:00,2024.000000,2497.760000,10.000000,0.50000,19966.500000,15729.670000,9144.150000,54.990000,99.990000,25.000000,12.000000,4.000000,2024.000000,2467.250000,1306.307143,13.615509,5966.052209
std,NaN,0.878628,380.901351,2.038508,0.16167,1154.811538,828.069100,420.487992,21.496639,28.424003,5.347633,3.406799,1.105429,0.878628,321.161767,118.880773,0.808802,149.829623

In [16]:
f_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Order_Date         10000 non-null  datetime64[ns]
 1   Year               10000 non-null  int64
 2   Month              10000 non-null  object
 3   Quarter            10000 non-null  object
 4   Season             10000 non-null  object
 5   Customer_Gender    10000 non-null  object
 6   Customer_Segment   10000 non-null  object
 7   Region             10000 non-null  object
 8   Country            10000 non-null  object
 9   Category           10000 non-null  object
 10  Sub_Category       10000 non-null  object
 11  Product_Name       10000 non-null  object
 12  Unit_Price         10000 non-null  float64
 13  Quantity           10000 non-null  int64
 14  Discount           10000 non-null  float64
 15  Revenue            10000 non-null  float64
 16  Cost               10000 non-null  float64
 17  Profit             10000 non-null  float64
 18  Profit_Margin_%    10000 non-null  float64
 19  Shipping_Cost      10000 non-null  float64
 20  Shipping_Method    10000 non-null  object
 21  Shipping_Days      10000 non-null  int64
 22  Payment_Method     10000 non-null  object
 23  Order_Status       10000 non-null  object
 24  Order_Month        10000 non-null  int32
 25  Order_Quarter      10000 non-null  int32
 26  Order_Year         10000 non-null  int32
 27  revenue_per_unit   10000 non-null  float64
 28  profit_per_unit    10000 non-null  float64
 29  scost_per_revenue  10000 non-null  float64
 30  net_revenue        10000 non-null  float64
dtypes: datetime64[ns](1), float64(11), int32(3), int64(3), object(13)
memory usage: 2.3+ MB

In [17]:
f_data.to_csv("./data_folder/Feature_engineered_data.csv", index=False)