# 🌍 AI-Powered Customer Intelligence Platform

## Country Profitability Analysis for Global E-Commerce Expansion

### Business Problem

A Chinese e-commerce company plans to expand its operations into a new Country. However, launching in every country is expensive and risky. The company needs a data-driven approach to identify which country is the most profitable and offers the greatest business potential.

This project analyzes historical e-commerce sales data from 2021 to 2024 to determine which country generates the highest revenue and profit. The insights will help the business stakeholders make informed decisions about market expansion and resource allocation.

## Project Objective

The primary objective of this project is to identify the countries that would be the most profitable for launching or expanding an e-commerce business.

To achieve this, the project will analyze sales performance across countries and answer key business questions using exploratory data analysis, statistical methods, and machine learning.


## Business Questions

This project aims to answer the following questions:

1. Which country generates the highest total revenue?
2. Which country generates the highest profit?
3. Which country have the highest average order value?
4. Which product categories perform best in each country?
5. Which regions contribute the largest share of global sales?
6. How have sales changed between 2021 and 2024?
7. Which country has the greatest long-term business potential?
8. What recommendations can be made for future market expansion?
   

## Dataset

**Dataset Name**

Global E-Commerce Sales Dataset (Synthetic) | 2021–2024

**Description**

This synthetic dataset simulates realistic e-commerce transactions from a fictional global online retailer operating in 20 countries across four major regions between January 2021 and December 2024.

The dataset contains information about:

* Order_ID', 'Order_Date', 'Quarter', 'Season', 'Customer_ID',
* 'Customer_Gender', 'Customer_Segment', 'Region', 'Country',
* 'Category', 'Sub_Category', 'Product_Name', 'Shipping_Method',
* 'Payment_Method', 'Order_Status', Year', 'Month', 'Unit_Price',
* 'Quantity', 'Discount', 'Revenue', 'Cost', 'Profit',
* 'Profit_Margin_%', 'Shipping_Cost', 'Shipping_Days'
    
The data is from kaggle Global E-Commerce Sales Dataset (Synthetic) | 2021–2024 https://www.kaggle.com/datasets/abdelfattahibrahim/global-e-commerce-sales-dataset-20212024/data

## Expected Deliverables

At the end of this project, the analysis will provide:

* A ranked list of the most profitable countries
* Interactive visualizations of global sales performance
* Country-level business insights
* Revenue and profitability dashboards
* Actionable recommendations for business expansion


## Tools and Technologies

* Python
* Pandas
* NumPy
* Matplotlib
* Plotly
* Scikit-learn
* Jupyter Notebook
* git and GitHub
* streamlit


## Data Science Workflow

This project will follow this data science workflow:

1. Data Collection
2. Data Cleaning
3. Exploratory Data Analysis (EDA)
4. Feature Engineering
5. Predictive Modeling
6. Visualization
7. Business Recommendations


## Success Criteria

The project will be considered successful if it can identify with 85% accuracy the countries that offer the strongest business opportunities based on historical sales performance and provide evidence-based recommendations for international expansion.

In [7]:
#importing the libraries needed for th project
import pandas as pd
import numpy as np
import matplotlib.pyplot as mat

# Data collection

In [8]:
#reading the data in jupyter notebook
data = pd.read_csv("../data_folder/ecommerce_sales_dataset.csv")

In [9]:
# viewing the top 4 rows in our data
data.head(4)

,Order_ID,Order_Date,Year,Month,Quarter,Season,Customer_ID,Customer_Gender,Customer_Segment,Region,...,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Method,Shipping_Days,Payment_Method,Order_Status
0,ORD-000001,2023-01-18,2023,1,Q1,Winter,CUST-02791,Male,New,North America,...,0.00,3642.80,2444.11,1198.69,32.91,2.25,Economy,4,Google Pay,Delivered
1,ORD-000002,2023-11-13,2023,11,Q4,Fall,CUST-02763,Female,Regular,North America,...,0.25,33.88,28.32,5.56,16.41,4.72,Economy,5,Credit Card,Delivered
2,ORD-000003,2022-04-28,2022,4,Q2,Spring,CUST-05729,Male,Regular,North America,...,0.00,241.30,161.41,79.89,33.11,13.28,Standard,8,Credit Card,Processing
3,ORD-000004,2021-10-22,2021,10,Q4,Fall,CUST-06490,Female,Regular,Asia,...,0.00,654.50,369.16,285.34,43.60,31.11,Express,16,Google Pay,Processing

In [10]:
#viewing 2 rows of our data from the last row
data.tail(2)

,Order_ID,Order_Date,Year,Month,Quarter,Season,Customer_ID,Customer_Gender,Customer_Segment,Region,...,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Method,Shipping_Days,Payment_Method,Order_Status
9998,ORD-009999,2021-09-22,2021,9,Q3,Fall,CUST-04665,Male,Regular,North America,...,0.25,1550.95,1131.45,419.50,27.05,15.81,Standard,7,Apple Pay,Delivered
9999,ORD-010000,2023-03-25,2023,3,Q1,Spring,CUST-05360,Female,Regular,Middle East,...,0.10,111.32,79.40,31.92,28.67,20.67,Express,9,Google Pay,Delivered

In [11]:
data.describe()

,Year,Month,Unit_Price,Quantity,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Days
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,2022.756300,6.604300,236.307452,2.731300,0.17675,528.438770,384.674939,143.763831,23.648594,32.299889,11.436100
std,0.878628,3.406799,380.901351,2.038508,0.16167,1154.811538,828.069100,420.487992,21.496639,28.424003,5.347633
min,2021.000000,1.000000,10.010000,1.000000,0.00000,5.330000,4.850000,-1572.900000,-50.000000,2.000000,3.000000
25%,2022.000000,4.000000,42.767500,1.000000,0.00000,67.227500,50.017500,9.007500,13.497500,8.260000,7.000000
50%,2023.000000,7.000000,92.495000,2.000000,0.15000,164.600000,121.395000,34.745000,28.330000,20.300000,10.000000
75%,2023.000000,10.000000,221.822500,4.000000,0.30000,469.952500,339.020000,118.475000,39.082500,50.362500,15.000000
max,2024.000000,12.000000,2497.760000,10.000000,0.50000,19966.500000,15729.670000,9144.150000,54.990000,99.990000,25.000000

In [26]:
# information about our data features
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 26 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Order_ID          10000 non-null  object
 1   Order_Date        10000 non-null  datetime64[ns]
 2   Year              10000 non-null  int64
 3   Month             10000 non-null  int64
 4   Quarter           10000 non-null  object
 5   Season            10000 non-null  object
 6   Customer_ID       10000 non-null  object
 7   Customer_Gender   10000 non-null  object
 8   Customer_Segment  10000 non-null  object
 9   Region            10000 non-null  object
 10  Country           10000 non-null  object
 11  Category          10000 non-null  object
 12  Sub_Category      10000 non-null  object
 13  Product_Name      10000 non-null  object
 14  Unit_Price        10000 non-null  float64
 15  Quantity          10000 non-null  int64
 16  Discount          10000 non-null  float64
 17  Revenue           10000 non-null  float64
 18  Cost              10000 non-null  float64
 19  Profit            10000 non-null  float64
 20  Profit_Margin_%   10000 non-null  float64
 21  Shipping_Cost     10000 non-null  float64
 22  Shipping_Method   10000 non-null  object
 23  Shipping_Days     10000 non-null  int64
 24  Payment_Method    10000 non-null  object
 25  Order_Status      10000 non-null  object
dtypes: datetime64[ns](1), float64(7), int64(4), object(14)
memory usage: 2.0+ MB

In [27]:
# total number of our data
data.size

260000

In [28]:
#viewing number of rows and columns 
data.shape

(10000, 26)

In [29]:
# viewing data numerical column
numerical_columns = data.select_dtypes(include=['number']).columns.tolist()
print(numerical_columns)

['Year', 'Month', 'Unit_Price', 'Quantity', 'Discount', 'Revenue', 'Cost', 'Profit', 'Profit_Margin_%', 'Shipping_Cost', 'Shipping_Days']

In [30]:
# viewing data categorical column
categorical_columns = data.select_dtypes(include=['object', 'category']).columns.tolist()
print(categorical_columns)

['Order_ID', 'Quarter', 'Season', 'Customer_ID', 'Customer_Gender', 'Customer_Segment', 'Region', 'Country', 'Category', 'Sub_Category', 'Product_Name', 'Shipping_Method', 'Payment_Method', 'Order_Status']

In [31]:
data.head(1)

,Order_ID,Order_Date,Year,Month,Quarter,Season,Customer_ID,Customer_Gender,Customer_Segment,Region,...,Discount,Revenue,Cost,Profit,Profit_Margin_%,Shipping_Cost,Shipping_Method,Shipping_Days,Payment_Method,Order_Status
0,ORD-000001,2023-01-18,2023,1,Q1,Winter,CUST-02791,Male,New,North America,...,0.0,3642.8,2444.11,1198.69,32.91,2.25,Economy,4,Google Pay,Delivered

In [32]:
# checking for null values in our data
data.isnull().sum()

# no null data

Order_ID            0
Order_Date          0
Year                0
Month               0
Quarter             0
Season              0
Customer_ID         0
Customer_Gender     0
Customer_Segment    0
Region              0
Country             0
Category            0
Sub_Category        0
Product_Name        0
Unit_Price          0
Quantity            0
Discount            0
Revenue             0
Cost                0
Profit              0
Profit_Margin_%     0
Shipping_Cost       0
Shipping_Method     0
Shipping_Days       0
Payment_Method      0
Order_Status        0
dtype: int64

In [33]:
data.duplicated().sum()

np.int64(0)

In [34]:
# to convert my date from string to datetime
data['Order_Date'] = pd.to_datetime(data['Order_Date'])

In [35]:
date_columns = data.select_dtypes(include=['datetime']).columns.tolist()
print(date_columns)

['Order_Date']

In [36]:
type(data["Order_Date"])

pandas.core.series.Series

In [37]:
data["Order_Date"]

0      2023-01-18
1      2023-11-13
2      2022-04-28
3      2021-10-22
4      2023-08-06
          ...
9995   2023-07-15
9996   2022-01-01
9997   2024-04-23
9998   2021-09-22
9999   2023-03-25
Name: Order_Date, Length: 10000, dtype: datetime64[ns]

## List of all the the countries
* the goal is to find which of these countries has the highest profitablility

In [38]:
data["Country"].unique()

array(['Mexico', 'USA', 'Canada', 'Japan', 'France', 'China', 'Germany',
       'Jordan', 'Italy', 'Egypt', 'Kuwait', 'Singapore', 'UAE',
       'South Korea', 'Saudi Arabia', 'UK', 'Spain', 'India'],
      dtype=object)

In [39]:
data["Country"].nunique()

18